modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="plants_vs_hostiles"
version="1.0.0"
displayName="Plants Vs. Hostiles"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="newvi, MCreator"

[[dependencies.plants_vs_hostiles]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




